export const colores=[
    {
       fondo:'bg-red-500',
       texto:'text-white'
    },
    {
       fondo:'bg-green-700',
       texto:'text-white'
    },
    {
       fondo:'bg-blue-800',
       texto:'text-white'
    },
    {
       fondo:'bg-orange-400',
       texto:'text-black'
    },
    {
       fondo:'bg-violet-500',
       texto:'text-black'
    },
    {
       fondo:'bg-rose-300',
       texto:'text-black'
    },
    {
       fondo:'bg-yellow-300',
       texto:'text-black'
    },
    {
       fondo:'bg-amber-700',
       texto:'text-white'
    },
    {
       fondo:'bg-blue-300',
       texto:'text-black'
    },
    {
       fondo:'bg-slate-400',
       texto:'text-white'
    },
    {
       fondo:'bg-red-800',
       texto:'text-white'
    },
    {
       fondo:'bg-lime-400',
       texto:'text-black'
    },
 ]